### ISSUE TITLE
Looping Error

### ISSUE THREAD

**Issue by rwilleynyc** [learn-co-curriculum/dsc-0-01-17-looping-over-collections#1]
For the following code in the lab, [index] should be [i], or i should be index:

for i in list(range(0, len(countries))):
    print(cities[index]+",", countries[index])

**Comment by rnguyen832** [comment]
I approve. This could either be very frustrating for someone who isn't quite familiar enough with code, or a very beneficial lesson on syntax.

**Comment by PeterBell** [comment]
Fixed by @sanpietro !
